import Head from 'next/head' 
import { Inter } from '@next/font/google' 
import Layout from '@/components/Layout/layout'

const inter = Inter({ subsets: ['latin'] })

export default function PlanDuSite() {
  return (
    <>
      <Head>
        <title>Plan du site</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Layout>
        <h1>Plan du site</h1>
      </Layout>
    </>
  )
}
